---
# Docker (used by image_registry)
- name: Include containerd defauts
  include_vars:
    file: roles/containerd/defaults/main.yml
    name: containerd_defaults

- name: Install Docker packages
  package:
    name: "{{ docker_packages[ansible_os_family] }}"
    state: present
  module_defaults:
    yum: {lock_timeout: "{{ yum_lock_timeout }}"}

- include_tasks: configure-docker.yml
