---
# Handlers for Kafka

- name: Restart kafka
  service:
    name: kafka
    state: restarted
    enabled: yes
  retries: 10
  delay: 10

- name: Restart prometheus
  become: true
  systemd:
    daemon_reload: true
    name: prometheus
    state: restarted
  delegate_to: "{{ node }}"
  loop_control:
    loop_var: node
  loop: "{{ groups.prometheus }}"
