---
- name: Get information on installed packages
  package_facts:
    manager: auto

- name: Remove Docker
  when:
    - inventory_hostname not in groups.image_registry
    - ansible_facts.packages['docker-ce'] is defined
  block:
  - name: Stop Kubelet before Docker removal
    systemd:
      name: kubelet
      state: stopped
    notify:
    - Restart kubelet

  - name: Remove Docker
    include_role:
      name: docker
      tasks_from: remove-docker.yml

- name: Install containerd.io package
  package:
    name: "{{ _packages[ansible_os_family] }}"
    state: present
  vars:
    _packages:
      Debian:
        - containerd.io={{ containerd_version }}-*
      RedHat:
        - containerd.io-{{ containerd_version }}
  module_defaults:
    yum: { lock_timeout: "{{ yum_lock_timeout }}",
           allow_downgrade: true }
    apt: { allow_downgrade: true }

- name: Configure prerequisites
  include_tasks: configure-prerequisites.yml

- name: Configure containerd
  include_tasks: configure-containerd.yml

- name: Configure kubelet-env
  include_tasks: configure-kubelet-env.yml

- name: Provide crictl.yaml file
  copy:
    src: crictl.yaml
    dest: /etc/crictl.yaml
    owner: root
    group: root
    mode: u=rw,go=r
